(* ::Package:: *)

(* Autogenerated Package *)

ChemSpectrum::usage="Object head for wrapping up spectral data";


Begin["`Private`"];


(* ::Text:: *)
(*
	This is empty. I just wanted ChemSpectrum declared out here.
*)



ChemSpectrumCopy;


End[];



