(* ::Package:: *)

(* Autogenerated Package *)

ChemSpectrum::usage="Object head for wrapping up spectral data";


Begin["`Private`"];


(* ::Subsection:: *)
(*Formatting*)



(* ::Subsubsection::Closed:: *)
(*Continuous*)



$specIcon=
  Image[
    Import@PackageFilePath["Resources", "Icons", "ContinuousSpectrumIcon.png"],
    ImageSize->{32,32}
    ];


Format[ChemSpectrum[data_List]]:=
  RawBoxes@BoxForm`ArrangeSummaryBox[
    "ChemSpectrum",
    ChemSpectrum[data],
    $specIcon,
    {
      BoxForm`MakeSummaryItem[{"Points: ",Length@data},StandardForm]
      },
    {
      BoxForm`MakeSummaryItem[
        {"Scanning Range: ",Round[MinMax@data[[All,1]],.001]},
        StandardForm],
      BoxForm`MakeSummaryItem[
        {"Intensity Range: ",Round[MinMax@data[[All,2]],.001]},
        StandardForm]
      },
    StandardForm
    ];


(* ::Subsubsection::Closed:: *)
(*Discrete*)



$discSpecIcon=
  Image[
    Import@PackageFilePath["Resources", "Icons", "DiscreteSpectrumIcon.png"],
    ImageSize->{32,32}
    ];


Format[ChemSpectrum[data_Association]]:=
  RawBoxes@BoxForm`ArrangeSummaryBox[
    "ChemSpectrum",
    ChemSpectrum[data],
    $discSpecIcon,
    {
      BoxForm`MakeSummaryItem[{"Transitions: ",
        Length@Lookup[data,"Frequencies",{}]},StandardForm]
      },
    {
      BoxForm`MakeSummaryItem[
        {"Scanning Range: ",Round[MinMax@Lookup[data,"Frequencies",{-1}],.001]},
        StandardForm],
      BoxForm`MakeSummaryItem[
        {"Intensity Range: ",Round[MinMax@Lookup[data,"Weights",{-1}],.001]},
        StandardForm]
      },
    StandardForm
    ];


(* ::Subsection:: *)
(*Object Definitions*)



(* ::Subsubsection::Closed:: *)
(*UpValues*)



(* ::Subsubsubsection::Closed:: *)
(*Normal*)



ChemSpectrum/:HoldPattern[Normal@ChemSpectrum[d_List]]:=
  d;
ChemSpectrum/:HoldPattern[Normal@ChemSpectrum[d_Association]]:=
  Thread@Lookup[d,{"Frequencies","Weights"}];


(* ::Subsubsubsection::Closed:: *)
(*Part*)



ChemSpectrum/:HoldPattern[Part[ChemSpectrum[d_List],i_Integer]]:=
  Part[d,i];
ChemSpectrum/:HoldPattern[Part[ChemSpectrum[d_List],s:_Span|_List]]:=
  ChemSpectrum[Part[d,s]];
ChemSpectrum/:HoldPattern[Part[ChemSpectrum[d_Association],spec_]]:=
  ChemSpectrum@(Part[#,spec]&/@d);


(* ::Subsubsubsection::Closed:: *)
(*Partition*)



ChemSpectrum/:HoldPattern[Partition[ChemSpectrum[d_List], s___]]:=
  ChemSpectrum/@Partition[d,s];
ChemSpectrum/:HoldPattern[Partition[ChemSpectrum[d_Association],spec___]]:=
  With[{v=Values@d,k=Keys@d},
    MapThread[
      ChemSpectrum@Association@Thread[k->{##}]&,
      Partition[#,spec]&/@v
      ]
    ];


(* ::Subsubsubsection::Closed:: *)
(*Length*)



ChemSpectrum/:HoldPattern[Length@ChemSpectrum[d_List]]:=
  Length@d;
ChemSpectrum/:HoldPattern[Length@ChemSpectrum[d_Association]]:=
  Length@d["Frequencies"];


(* ::Subsubsubsection::Closed:: *)
(*Range*)



ChemSpectrum/:HoldPattern[Range@ChemSpectrum[d_List]]:=
  MinMax@d[[All,1]];
ChemSpectrum/:HoldPattern[Range@ChemSpectrum[d_Association]]:=
  MinMax@d["Frequencies"];


(* ::Subsubsubsection::Closed:: *)
(*MinMax / Min / Max*)



ChemSpectrum/:HoldPattern[MinMax@ChemSpectrum[d_List]]:=
  MinMax@d[[All,2]];
ChemSpectrum/:HoldPattern[MinMax@ChemSpectrum[d_Association]]:=
  MinMax@d["Weights"];


ChemSpectrum/:HoldPattern[Max@ChemSpectrum[d_List]]:=
  First@MaximalBy[d,Last];
ChemSpectrum/:HoldPattern[Max@ChemSpectrum[d_Association]]:=
  First@MaximalBy[Thread[{d["Frequencies"],d["Weights"]}],Last];


ChemSpectrum/:HoldPattern[Min@ChemSpectrum[d_List]]:=
  First@MinimalBy[d,Last];
ChemSpectrum/:HoldPattern[Min@ChemSpectrum[d_Association]]:=
  First@MinimalBy[Thread[{d["Frequencies"],d["Weights"]}],Last];


(* ::Subsubsubsection::Closed:: *)
(*Lookup (note that in general this will fail... )*)



ChemSpectrum/:
  HoldPattern[Lookup[ChemSpectrum[d_Association],k_]]:=
    Lookup[d,k];
ChemSpectrum/:
  HoldPattern[Lookup[ChemSpectrum[d_Association],k_,def_]]:=
    Lookup[d,k,def];
ChemSpectrum/:
  HoldPattern[ChemSpectrum[d_Association][k__]]:=
    Fold[Lookup, d, {k}];


(* ::Subsubsubsection::Closed:: *)
(*Association*)



ChemSpectrum/:
  HoldPattern[Association@ChemSpectrum[d_List]]:=
    Thread[{"Frequencies","Weights"}->Thread[d,List]];
ChemSpectrum/:
  HoldPattern[Association@ChemSpectrum[d_Association]]:=
    d;


ChemSpectrum/:
  HoldPattern[Lookup[ChemSpectrum[d_List],k_]]:=
    Lookup[Association@ChemSpectrum[d],k];
ChemSpectrum/:
  HoldPattern[Lookup[ChemSpectrum[d_List],k_,def_]]:=
    Lookup[Association@ChemSpectrum[d],k,def];
ChemSpectrum/:
  HoldPattern[ChemSpectrum[d_List][k__]]:=
    ChemSpectrum[Association[ChemSpectrum[d]]][k]


(* ::Subsubsubsection::Closed:: *)
(*Interpolation*)



ChemSpectrum/:
  HoldPattern[Interpolation@ChemSpectrum[d_List]]:=
    Interpolation@d;
ChemSpectrum/:
  HoldPattern[Interpolation@ChemSpectrum[d_Association]]:=
    First@*First@*
      Nearest[Normal@GroupBy[Normal@ChemSpectrum[d],First]];


(* ::Subsubsubsection::Closed:: *)
(*MovingAverage*)



(* ::Subsubsubsection::Closed:: *)
(*MovingMap*)



(* ::Subsubsection::Closed:: *)
(*SubValues*)



(* ::Subsubsubsection::Closed:: *)
(*View*)



(* ::Subsubsubsection::Closed:: *)
(*Zoom*)



ChemSpectrum/:HoldPattern[ChemSpectrum[d_][range1_,range2_]]:=
  ChemSpectrumZoom[ChemSpectrum[d],{range1,range2}];


(* ::Subsubsubsection::Closed:: *)
(*LinePick*)



(* ::Subsubsubsection::Closed:: *)
(*Smooth*)



End[];



