(* ::Package:: *)

(* Autogenerated Package *)

(* ::Text:: *)
(*
	For now we\[CloseCurlyQuote]ll assume function output values are scalar
*)



GridFunctionObject::usage=
  "A object-oriented interface into functions defined over grids";


Begin["`Private`"];


RegisterInterface[
  GridFunctionObject,
  {"Grid", "Values"},
  "Validator"->
    GridFunctionObjectQ,
  "Constructor"->
    ConstructGridFunction,
  "MutationFunctions"->{"Keys"},
  "AccessorFunctions"->
    <|
      "Keys"->GFKeyPart, 
      "Parts"->GFPart
      |>,
  "NormalFunction"->GFArray,
  "Protect"->True
  ]


(* ::Subsection:: *)
(*Properties*)



(* ::Subsubsection::Closed:: *)
(*Properties*)



InterfaceAttribute[GridFunctionObject]@
  f_GridFunctionObject["Dimensions"]:=
    GridDimensions[f["Grid"]];
InterfaceAttribute[GridFunctionObject]@
  f_GridFunctionObject["Dimension"]:=
    GridDimension[f["Grid"]];
InterfaceAttribute[GridFunctionObject]@
  f_GridFunctionObject["MeshSpacings"]:=
    GridMeshSpacings[f["Grid"]];


InterfaceAttribute[GridFunctionObject]@
  f_GridFunctionObject["Points"]:=
    GFPoints[f];


(* ::Subsubsection::Closed:: *)
(*Method*)



InterfaceMethod[GridFunctionObject]@
  f_GridFunctionObject["Product"][o__GridFunctionObject]:=
    GFKroneckerProduct[f, o];
InterfaceMethod[GridFunctionObject]@
  f_GridFunctionObject["Plot"][ops___]:=
    GFPlot[f, ops];
InterfaceMethod[GridFunctionObject]@
  f_GridFunctionObject["Compile"][spec___]:=
    GFCompile[f, spec];
InterfaceMethod[GridFunctionObject]@
  g_GridFunctionObject["Slice"][n__Integer]:=
    GFSlice[g, n];


(* ::Subsubsection::Closed:: *)
(*Overrides*)



InterfaceOverride[GridFunctionObject]@
  Interpolation[
    f_GridFunctionObject,
    a___
    ]:=
    GFInterpolation[f, a];
InterfaceOverride[GridFunctionObject]@
  MinMax[
    f_GridFunctionObject
    ]:=
    GFMinMax[f];
InterfaceOverride[GridFunctionObject]@
  Map[
    fn_,
    f_GridFunctionObject
    ]:=
    GFMap[fn, f];
InterfaceOverride[GridFunctionObject]@
  Translate[
    f_GridFunctionObject,
    n_
    ]:=
    With[{res=GFShift[f, n]},
      res/;Head[res]=!=GFShift
      ];
InterfaceOverride[GridFunctionObject]@
  Scale[
    f_GridFunctionObject,
    n_
    ]:=
    With[{res=GFScale[f, n]},
      res/;Head[res]=!=GFScale
      ];
InterfaceOverride[GridFunctionObject]@
  Rescale[
    f_GridFunctionObject,
    a__
    ]:=
    GFRescale[f, a];
InterfaceOverride[GridFunctionObject]@
  Threshold[
    f_GridFunctionObject,
    a__
    ]:=
    GFChop[f, a]


End[];



