(* ::Package:: *)

(* Autogenerated Package *)

WavefunctionsObject::usage=
  "An object-oriented interface into wavefunction stuff";


Begin["`Private`"];


RegisterInterface[
  WavefunctionsObject,
  {"Wavefunctions", "Energies"},
  "Validator"->
    WavefunctionsObjectQ,
  "Constructor"->
    ConstructWavefunctions,
  "AccessorFunctions"->
    <|
      "Parts"->WFPart,
      "Keys"->WFKeyPart
      |>,
  "NormalFunction"->(WFNormal)
  ]


(* ::Subsection:: *)
(*Properties*)



(* ::Subsubsection::Closed:: *)
(*Attributes*)



InterfaceAttribute[WavefunctionsObject]@
  c_WavefunctionsObject["Grid"]:=
  c["Wavefunctions"][[1]]["Grid"];


(* ::Subsubsection::Closed:: *)
(*Methods*)



InterfaceMethod[WavefunctionsObject]@
  c_WavefunctionsObject["Plot"][o___]:=
  WFPlot[c, o]


InterfaceMethod[WavefunctionsObject]@
  c_WavefunctionsObject["Product"][o___]:=
  WFProduct[c, o]


InterfaceMethod[WavefunctionsObject]@
  c_WavefunctionsObject["ExpectationValues"][o___]:=
  WFExpectationValues[c, o]


End[];



