(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



ChemDVRBegin[];


ProlateTopDVRK::usage="The adjusted kinetic operator form of SphericalDVRK";
$ProlateTopDVR::usage="The output association for class making";


ChemDVRNeeds/@{"SphericalDVR","LegendreDVR","RadialDVR","MeyerDVR"}


Begin["`Private`"];


Clear["ProlateTopDVRK"]
	Options[ProlateTopDVRK]=Flatten[{
			Options[SphericalDVRK],
			"RotationalA"->10,
			"RotationalB"->3,
			"RotationalC"->1
			}];
	ProlateTopDVRK[grid_,ops:OptionsPattern[]]:=
		With[{
			T=Last@grid,
			X=DeleteDuplicates/@Transpose@Flatten[First@grid,Depth@First@grid-3]},
			With[{
				rX=X[[1]],\[Phi]X=X[[2]],\[Theta]X=X[[3]],
				rK=RadialDVRK[X[[1]]],\[Phi]K=MeyerDVRK[X[[2]]],\[Theta]K=LegendreDVRK[{X[[3]],T}]
				},
				With[{
					rN=Length@rK,\[Phi]N=Length@\[Phi]K,\[Theta]N=Length@\[Theta]K,
					\[HBar]=OptionValue@"\[HBar]",
					Am=OptionValue["RotationalA"],
					Bm=OptionValue["RotationalB"],
					Cm=OptionValue["RotationalC"]
					},
					With[{
						rf=Function[k,1+Mod[Floor[(k-1)/\[Phi]N],rN]],
						ff=Function[k,1+Mod[k-1,\[Phi]N]],
						qf=Function[k,1+Floor[(k-1)/(rN*\[Phi]N)]],
						n=rN*\[Phi]N*\[Theta]N
						},
						\[HBar]*ParallelTable[
								KroneckerDelta[ff[i],ff[j]]*KroneckerDelta[qf[i],qf[j]]*
									rK[[ rf[i],rf[j] ]]+
								KroneckerDelta[rf[i],rf[j]]*KroneckerDelta[qf[i],qf[j]]
									*(Am-1/2(Bm+Cm))*\[Phi]K[[ ff[i],ff[j] ]]+
								KroneckerDelta[ff[i],ff[j]]*KroneckerDelta[rf[i],rf[j]]*
									(1/2(Bm+Cm))*\[Theta]K[[ qf[i],qf[j] ]],
							{i,n},
							{j,n}
							]
						]
					]
				]
			]


End[];


ChemDVREnd[];


$ProlateTopDVR=
	ReplacePart[$SphericalDVR,
		{
			"Name"->"Plane Point",
			"KineticEnergy"->ProlateTopDVRK
			}]



